apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: limitedpods.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: limitedpod
    plural: limitedpods
    singular: limitedpod
    shortNames:
      - limp
      - limps
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Message
          type: string
          priority: 0
          jsonPath: .status.message
        - name: Memory
          type: string
          priority: 0
          jsonPath: .status.memory
        - name: CPU
          type: string
          priority: 0
          jsonPath: .status.cpu
        - name: Status
          type: string
          priority: 0
          jsonPath: .status.phase